### ISSUE TITLE
Làm thế nào để backup config vim đến github?

### ISSUE THREAD

**Issue by mrhieu059** [HadesD/dotfiles#1]
Như tiêu đề, mình thấy bạn có repository để lưu trữ những file config, vậy bạn có thể hướng dẫn cho mình được không?
Hay chỉ như bình thường là up nó lên git thôi? Mình muốn sử dụng git nhưng thấy mơ hồ quá .
Mình có search thì có thuật ngữ dotfile rồi symlink gì gì đó?
Có phải là mình config file vimrc với bất kì tên nào thì khi mình symlink file đó đến ~/.vimrc thì nó đều nhận thông tin từ file mình config chứ không phải vimrc?
Sorry vì câu hỏi thiếu hiểu biết, mong bạn hướng dẫn thêm

**Comment by HadesD** [comment]
Sorry bạn vì trả lời chậm (mình không nghĩ sẽ có người gửi issue nên cũng không để ý luôn 🙄 )
Đây là repo lưu trữ tất cả các file dot dùng cho linux là chính, ban đầu repo này mang tên là `.vim`, nó chỉ có nhiệm vụ lưu config của VIM thôi, lúc đó chỉ cần clone về máy là bạn có thể sử dụng được luôn, vì VIM nó đọc file ~/.vimrc đầu tiên, sau đó đọc file ~/.vim/vimrc, vậy nên clone về và tạo symlink tới ~/.vim/vimrc là mở vim dùng luôn

Tuy nhiên, sau này mình dùng thêm TMUX, Z-SHELL (ZSH) nên mới nghĩ "Không nhẽ mỗi thằng lại phải tạo 1 repo mới??". Cho nên mình tạo repo này để gộp hết lại, vì chắc chắn những người sử dụng repo này sẽ dần đi lên sử dụng những thứ y hệt mình thôi.

Trong linux nó có chức năng symlink rất hay, hay hơn cái short-cut của windows nhiều. Chỉ cần tạo symlink là các phần mềm khi đọc file/folder đó có thể đọc được ngay nội dung file gốc, mặc dù path đã thay đổi. Vậy nên chỉ cần clone repo này về máy, sau đó chạy symlink folder .vim ra ngoài ~/.vim là có thể dùng vim như thường

**Comment by IamHuskar** [comment]
抱歉在这里留言。因为主页没看到联系方式。想请问一下你 之前 编译的剑网3的代码，能编译过去吗？因为我下载的也是缺少了核心库。
